# Generated by Django 3.2.7 on 2021-10-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_clinic', '0003_auto_20211015_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='patient_histories',
            field=models.ManyToManyField(blank=True, to='dentist_clinic.PatientHistory'),
        ),
    ]
