# Generated by Django 3.2.7 on 2021-10-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_clinic', '0004_alter_userdata_patient_histories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='appointments',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dentist_clinic.appointment'),
        ),
    ]
